inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "spanner-activerecord.gemspec"
    - "Rakefile"
    - "test/**/*"
    - "bin/*"
  Include:
    - "lib/**/*.rb"

Documentation:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/BlockLength:
  Max: 30
